print('Enter a number to be calculated with')
var1 = int(input())
print("Enter another number")
var2 = int(input())
print("Final number")
var3 = int(input())
print(var1,"plus",var2,"=", var1 + var2)
print(var2,"plus",var3,"=", var2 + var3)
print(var1,"subtracted by 2","=", var1 - 2)
print(var1,"divided by",var3,"=", var1 / var3)
print(var2, "to the power of",var3,"=", var2 ** var3)
