num1 = int(input("Enter a number: "))
num2 = input("Enter another number: ")
totaladdition = num1 + int(num2)
totalsubtraction = num1 - int(num2)
totalmultiplication = num1 * int(num2)
totaldivision = num1 / int(num2)
totaldivisionint = num1 // int(num2)
remainderdivision = num1 % int(num2)
power = num1 ** int(num2)
print(f"Addition: {totaladdition}")
print(f"Subtraction: {totalsubtraction}")
print(f"Multiplication: {totalmultiplication}")
print(f"Division: {totaldivision}")
print(f"Division no decimals: {totaldivisionint}")
print(f"Remainder of division: {remainderdivision}")
print(f"Power: {power}")